### PR TITLE
Migrate to use v0.14 API

### PR DESCRIPTION
**Pull request by cosmo0920**
I've tried to migrate to use v0.14 Output Plugin API.
This PR contains major update change.
Could you bump up minor version if releasing new version of gem?
And please refer http://docs.fluentd.org/v0.14/articles/plugin-update-from-v12 before release new version.

Thanks,

### CODE REVIEW

**Comment by wryun** [comment]
Awesome - looks great. Thanks for doing this; I've been meaning to get to it for a while...

I'll try to find time to look over it properly and do some testing in the next couple of days. Please bug me again if it's not out by next week.

**Comment by cosmo0920** [comment]
Thanks for your response.
Sure, I'll send ping if you or someone do nothing in few months.
I'm not hurry up to do this.
Note that Fluentd v0.14 is not stable for now -- still unstable -- and it will reached to be stable in 2017 Q3.

**Comment by cosmo0920** [comment]
Awesome. Thanks for merging. :smiley_cat:

**Comment by wryun** [comment]
Released as 0.3.0

**Pull request merged**
